backend:
  name: git-gateway
  branch: master
  repo: UjjalKar/anup-sites

media_folder: static/image
public_folder: /image

collections:
  - name: "blog"
    label: "Blog"
    folder: "src/posts"
    create: true
    slug: "{{slug}}"
    fields:
      - {
          label: "Template Key",
          name: "templateKey",
          widget: "hidden",
          default: "blog-post",
        }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Description", name: "description", widget: "text" }
      - { label: "Featured Post", name: "featuredpost", widget: "boolean" }
      - { label: "Featured Image", name: "featuredimage", widget: image }
      - { label: "category", name: "category", widget: "list" }
      - { label: "Body", name: "body", widget: "markdown" }
      - { label: "Tags", name: "tags", widget: "list" }
      - { lable: "seoTags", name: "seoTags", widget: "list" }
      - {
          label: "Author",
          name: "author",
          widget: "relation",
          collection: "authors",
          searchFields: ["title", "firstName", "lastName"],
          valueField: "title",
        }
  - name: "authors"
    label: "Authors"
    folder: "src/authors"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Layout", name: "layout", widget: "hidden", default: "author" }
      - { label: "Full Name", name: "title", widget: "string" }
      - { label: "First Name", name: "firstName", widget: "string" }
      - { label: "Last Name", name: "lastName", widget: "string" }
      - { label: "Position", name: "position", widget: "string" }
      - { label: "Profile Picture", name: "profilePicture", widget: "image" }
      - { label: "Email", name: "email", widget: "string" }
  - name: "ourproducts"
    label: "Our Products"
    folder: "src/products"
    create: true
    identifier_field: productName
    slug: "{{slug}}"
    fields:
      - { label: "Product Name", name: "productName", widget: "string" }
      - {
          label: "Poduct Description",
          name: "productDescription",
          widget: "string",
        }
      - { label: "Product Image", name: "productImage", widget: "image" }
      - {
          label: "Product Category",
          name: "productCategory",
          widget: "list",
          field:
            { label: "Category Name", name: "categoryName", widget: "string" },
        }
      - { label: "Price", name: "Price", widget: "number" }
      - { label: "Product Content", name: "productContent", widget: "markdown" }
